# Site settings
title: Yuan's Blog
SEOTitle: 元紀錄 | Yuan's Blog
header-img: img/home-bg.jpg
email: yuan129931@gmail.com
description: "你好，這裡是@Yuan的部落格,前矩陣號youtube經營者,AI深度原住民,熱愛學習一切新事物。持續學習GPT / LLM / Cursor / Dify / GPT_sovits / Stable Diffusion…等中,我會分享我對AI 獨立開發 投資的學習經驗總結和進度，也會分享世界正在發生什麼，以及如何應對"

keyword: "陳脩元, DDChen666, DDChen, Daniel, daniel, @HSIU YUAN, Yuan, Yuan Blog, 博客, 部落格, 個人網站, Web, AI, ChatGPT, 獨立開發, 前端, 賺錢, youtube"
url: "https://ddchen666.github.io/" # your host, for absolute URL
baseurl: "" # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
# 社交媒體帳號設置
instagram_username: danielchen_16888 # Instagram 用戶名
facebook_username: DanielChen16888 # Facebook 頁面名稱
github_username: DDChen666 # GitHub 用戶名
twitter_username: chen79639ddc # Twitter/X 用戶名
linkedin_username: hsiu-yuan-c-b10143117 # LinkedIn 個人資料 ID
threads_username: danielchen_16888 # Threads 用戶名
# 如果不使用某個平台，在前面加 # 註釋掉
# weibo_username: your_weibo_username
# zhihu_username: your_zhihu_username

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
    "README.zh.md",
    "vendor",
    "Gemfile",
    "Gemfile.lock",
  ]
anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Disqus settings
disqus_username: yuan-blog # 你需要在 disqus.com 註冊這個用戶名

# Netease settings
netease_comment: false

# Analytics settings
# Baidu Analytics
# ba_track_id: [your track id]

# Google Analytics
# ga_track_id: "UA-xxxxxx-xx" # 請替換為你的 Google Analytics ID
# ga_domain: ddchen666.github.io

# Sidebar settings
sidebar: true # whether or not using Sidebar.
sidebar-about-description: "永不停止學習,永不停止行動,迎接技術爆炸！願你我都能過上想要的生活 <br> AI 深度原住民 @ Yuan's Blog"
sidebar-avatar: /img/avatar-yuan-home.jpg # use absolute URL, seeing it's used in both `/` and `/about/`

# Featured Tags
featured-tags: true # whether or not using Feature-Tags
featured-condition-size: 1 # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false

# Friends - 自定義友情鏈接
friends:
  [
    { title: "OpenAI", href: "https://openai.com/" },
    { title: "GitHub", href: "https://github.com/" },
    { title: "Cursor", href: "https://cursor.sh/" },
    { title: "Dify", href: "https://dify.ai/" },
    { title: "Stable Diffusion", href: "https://stability.ai/" },
    { title: "Hugging Face", href: "https://huggingface.co/" }
  ]
